name: hoomd-polymers 
channels:
  - conda-forge
dependencies:
  - foyer
  - freud
  - gsd
  - hoomd>3.7=*cpu*
  - mbuild
  - numpy
  - pip
  - pytest
  - pytest-cov
  - python=3.9
  - signac=1.7.0
  - signac-flow=0.18.1
  - unyt
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/mosdef-hub/gmso.git@main
